docker-compose-yaml: docker-compose.yml

project: ${LAGOON_PROJECT}

environments:
  main:
    routes:
      - nginx:
        - "${LAGOON_ROUTE}":
            tls-acme: true
            insecure: Redirect
