docker-compose-yaml: docker-compose.yml

project: static-site

tasks:
  post-rollout:
    - run:
        name: Testing the environment
        command: curl localhost:8080 -I
        service: nginx

environments:
  main:
    routes:
      - nginx:
        - "${LAGOON_ROUTE}":
            tls-acme: true
            insecure: Redirect
