docker-compose-yaml: docker-compose.yml

project: static-site

environments:
  '*':
    routes:
      - nginx:
          - "nginx.${LAGOON_ENVIRONMENT}.demo-annai-static-site.jp1.amazee.io":
              tls-acme: true
              insecure: Redirect
              basic_auth:
                enabled: true
                username: "${BASIC_AUTH_USERNAME}"
                password: "${BASIC_AUTH_PASSWORD}"
