x-volumes:
  &default-volumes
    volumes:
      - ./src:/app/src:delegated

x-environment:
  &default-environment
    LAGOON_ROUTE: &default-url http://demo-annai-static-site.docker.amazee.io

x-user:
  &default-user
    user: '1000'

services:
  nginx:
    build:
      context: .
      dockerfile: lagoon/nginx.dockerfile
    labels:
      lagoon.type: nginx
      lagoon.project: static-site
      lagoon.basic_auth: true
    << : [*default-volumes, *default-user]
    ports:
      - "8080"
    environment:
      << : *default-environment
      LAGOON_LOCALDEV_URL: *default-url
    networks:
      - amazeeio-network
      - default

networks:
  amazeeio-network:
    external: true
