server {
    listen 8080 default_server;
    server_name *.demo-annai-static-site.jp1.amazee.io
                demo-annai-static-site.docker.amazee.io;

    root /app/src;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
        allow all;
    }
}

server {
    listen 50000;
    server_name _;

    location /nginx_status {
        stub_status on;
        access_log off;
        allow all;
    }
}
