server {
    listen 8080;
    server_name nginx.main.demo-annai-static-site.jp1.amazee.io;

    user 1000;

    root /app/src;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        allow all;
    }

    location /nginx_status {
        stub_status on;
        access_log off;
        allow all;
    }
}
